# Generated by Django 2.1.7 on 2019-03-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('BrandName', models.CharField(max_length=100)),
                ('ModelNo', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('ItemWeight', models.IntegerField(max_length=100)),
                ('Size', models.CharField(max_length=100)),
                ('Wattage', models.CharField(max_length=100)),
                ('ProductColor', models.CharField(max_length=100)),
                ('StandardPrice', models.CharField(max_length=100)),
                ('GST', models.CharField(max_length=100)),
                ('Total', models.CharField(max_length=100)),
                ('ProductImage', models.ImageField(upload_to='images')),
            ],
        ),
    ]
