# Generated by Django 2.1.7 on 2019-04-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductImage',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
